import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

// Offline after first load. At build time, writes sw.js with the exact list of built files, so the
// whole app is cached on the first visit and a reload with no signal still works. No extra dependency.
function offlineServiceWorker(): Plugin {
  return {
    name: 'tuwulira-offline-sw',
    apply: 'build',
    generateBundle(_, bundle) {
      const files = ['./', './index.html', ...Object.keys(bundle).map((f) => `./${f}`)];
      // File names carry content hashes, so a hash of the list changes whenever the app changes.
      let h = 0;
      for (const ch of files.join('|')) h = (Math.imul(31, h) + ch.charCodeAt(0)) | 0;
      const version = (h >>> 0).toString(36);
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: `// Generated by vite.config.ts. Cache-first app shell; nothing here talks to a server.
const CACHE = 'tuwulira-${version}';
const FILES = ${JSON.stringify(files)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) => hit || fetch(req).catch(() => (req.mode === 'navigate' ? caches.match('./') : Response.error())),
    ),
  );
});
`,
      });
    },
  };
}

// The web prototype reads shared logic and data from the repo root (app/, config/, rules/).
// `tsconfig` is pinned so files under app/ are not compiled with the Expo tsconfig (not installed here).
export default defineConfig({
  plugins: [react(), offlineServiceWorker()],
  tsconfig: 'tsconfig.json',
  base: './',
  server: { host: true, fs: { allow: ['..'] } },
});
